version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    env_file:
      - ./server/.env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - mongo

volumes:
  mongo-data: {}

# https://chatgpt.com/share/6817fa9d-05c4-8003-a12c-9e00846a87d4